export const CONTACT_LIST_SUCCESS = "CONTACT_LIST_SUCCESS";
export const FAV_CONTACT_LIST_SUCCESS = "FAV_CONTACT_LIST_SUCCESS";
export const CLEAR_CONCTACTS = "CLEAR_CONCTACTS";
export const CLEAR_FAV_CONCTACTS = "CLEAR_FAV_CONCTACTS";